### ISSUE TITLE
Some feedback to initial version

### ISSUE THREAD

**Issue by derberg** [twodrops/docs-as-code-manifesto#1]
I like the initiative. Btw is it already somewhere decided we say `docs as code` instead of `content as code`? 😄 

I have only one comment:

> Documents shall be written in human-readable formats like Markdown, reStructuredText, JSON etc. and not as binary formats or other machine-readable formats like XML. This keeps the documents as close as possible to humans, who shall maintain it.

One could argue that JSON is for humans. If it would be for humans, YAML would not get so popular. In general, when you look at JSON and YAML you think about the machine as it gives structure easy to read for the machine. Writing those, like writing AsyncAPI or OpenAPI from scratch using those formats is not fun 😅

**Comment by twodrops** [comment]
Thanks a lot @derberg for your feedback.

>is it already somewhere decided we say docs as code instead of content as code

Good question. There are some specific usages like `architecture-as-code` which I heard. The other one I have heard of is `everything-as-code` which seems to come more from CI/CD where infrastructure is stored as code. I would like to use a popular term but didn't find anything more popular than `docs-as-code`.

>One could argue that JSON is for humans

From a pure technical writing for a product documentation perspective, the Markdowns, reStructuredTexts etc. are enough. When we move to storing other engineering artifacts as code, we will surely have such "configuration" formats. Do you have a proposal to provide an example for this differently?

**Comment by derberg** [comment]
> From a pure technical writing for a product documentation perspective, the Markdowns, reStructuredTexts etc. are enough. 

The thing is I don't think this is a correct statement. I might misunderstand though. AsyncAPI/OpenAPI is part of product documentation, for me, they are pure technical writing, at least should. They give you reference documentation for the API. So they are not just configuration formats, they are as standard as Markdown from my point of view.  

So looking again at 

> Documents shall be written in human-readable formats like Markdown, reStructuredText, JSON 

I don't mind having JSON, or YAML there. I'm just afraid people may criticize `human-readable` part there. 
I honestly do not have any other idea than putting YAML there instead of JSON. While for JSON many will say that it is sometimes as complicated as XML, for YAML you can give good arguments that it is human-readable

**Comment by twodrops** [comment]
Ah got it. I thought you were hinting on removing JSON, YAML etc. all together. I will change it to YAML and see what the community says. Thanks.
